version: '3.4'

services:
  php:
    build: ./docker/php
    container_name: twity_php
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/srv/twity:rw,cached
      - ./vendor:/srv/twity/vendor:delegated
      - appdata:/srv/twity/var/cache/
      - appdata:/srv/twity/var/log/
      - appdata:/srv/twity/var/composer

  web:
    build: ./docker/nginx
    container_name: twity_nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/twity/public:ro
    ports:
      - "8080:80"

  mongo:
    image: mongo:4.0
    container_name: twity_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

  rabbit:
    image: rabbitmq:3-management
    container_name: twity_rabbit
    restart: always
    ports:
    - "8081:15672"
    - "5672:5672"

  maildev:
    image: djfarrelly/maildev
    container_name: twity_maildev
    ports:
    - "8082:80"

  mercure:
    image: dunglas/mercure
    container_name: twity_mercure
    environment:
      - JWT_KEY=fzed922Ndçdz8273
      - ALLOW_ANONYMOUS=1
      - CORS_ALLOWED_ORIGINS=*
#      - PUBLISH_ALLOWED_ORIGINS=http://localhost:3000
    ports:
      - "8083:80"


volumes:
  db-data: {}
  appdata: {}
